### ISSUE TITLE
Any information on how Kiwi was used in the Mars helicopter mission?

### ISSUE THREAD

**Issue by Qix-** [nucleic/kiwi#106]
Hey everyone, hope all's well.

Just received the Mars helicopter achievement for contributing to Kiwi and was curious if there was any more information on how, specifically, it was used.

Purely curious :) Pretty awesome nonetheless, I love this library and happy to see it get such recognition.

**Comment by zmughal** [comment]
Here is a list of repos: <https://docs.github.com/en/github/setting-up-and-managing-your-github-profile/personalizing-your-profile#list-of-qualifying-repositories-for-mars-2020-helicopter-contributor-badge>. Probably via Matplotlib?

**Comment by Qix-** [comment]
Did they include all sub-dependencies, too? It's not clear, it seems.

**Comment by MatthieuDartiailh** [comment]
Somehow they even included cppy so it seems they went quite far. Thanks for sharing the news, I may have missed it otherwise.

**Comment by sccolbert** [comment]
My best guess is that matplotlib was used somewhere in the R&D phase. Since
matplotlib uses kiwi, we were included.
