### ISSUE TITLE
Link to "seminal Cassowary paper"?

### ISSUE THREAD

**Issue by trusktr** [nucleic/kiwi#110]
The README mentions the "seminal Cassowary paper", but there is no link. Where is this paper?

**Comment by Qix-** [comment]
https://constraints.cs.washington.edu/solvers/cassowary-tochi.pdf

I believe they mean the original cassowary paper.

**Comment by MatthieuDartiailh** [comment]
That is indeed the right paper @Qix- . The original implementation aimed at being mathematically correct and for example used lexicographic ordering for strength. Kiwi decided to simply use number for strength (different enough to cause no overlap) which may mean that a lot of weak constraints may overcome a medium one but that is rarely a problem in practice and make the algorithm faster. If anybody feel like making a PR adding the reference feel free to do so or I will try to address it when I get a chance.
