### ISSUE TITLE
1.3.2 final tag is not on GitHub

### ISSUE THREAD

**Issue by QuLogic** [nucleic/kiwi#119]
Only the `1.3.2.rc1` tag is there.

**Comment by QuLogic** [comment]
Also, no release notes update it looks like?

**Comment by MatthieuDartiailh** [comment]
Will fix it soon. The rc is good so I forgot to tag the final one.

**Comment by MatthieuDartiailh** [comment]
I tagged 1.3.2 and added some release notes. Since nothing changes and I botched the version number previously the wheels won't be updated but that is minor.
