### ISSUE TITLE
Build fails with gcc on macOS

### ISSUE THREAD

**Issue by nilsvu** [nucleic/kiwi#126]
GCC doesn't have the `-stdlib` option, so this line is trouble:

https://github.com/nucleic/kiwi/blob/5d33a8e445bb440b53e70c361162d2719629c6c1/setup.py#L58

This came up at an installation with [Spack](https://github.com/spack/spack), so I suggest fixing the Spack package as well.

**Comment by MatthieuDartiailh** [comment]
This should now be fixed on main which uses the latest version of cppy in which I added the logic to add stdlibc only for clang on MacOS

**Comment by MatthieuDartiailh** [comment]
Fixed in 1.4.0
