### ISSUE TITLE
Cann't install on python 3.11b3

### ISSUE THREAD

**Issue by tomdog2016** [nucleic/kiwi#146]
python setup.py install
running install
running bdist_egg
running egg_info
writing UNKNOWN.egg-info\PKG-INFO
writing dependency_links to UNKNOWN.egg-info\dependency_links.txt
writing top-level names to UNKNOWN.egg-info\top_level.txt
reading manifest file 'UNKNOWN.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*.png' under directory 'docs\source'
no previously-included directories found matching '.git'
no previously-included directories found matching 'dist'
no previously-included directories found matching 'build'
no previously-included directories found matching 'docs\build'
adding license file 'LICENSE'
writing manifest file 'UNKNOWN.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_ext
creating build\bdist.win-amd64\egg
creating build\bdist.win-amd64\egg\kiwisolver
copying build\lib.win-amd64-3.11\kiwisolver\_cext.cp311-win_amd64.pyd -> build\bdist.win-amd64\egg\kiwisolver
creating stub loader for kiwisolver\_cext.cp311-win_amd64.pyd
byte-compiling build\bdist.win-amd64\egg\kiwisolver\_cext.py to _cext.cpython-311.pyc
creating build\bdist.win-amd64\egg\EGG-INFO
copying UNKNOWN.egg-info\PKG-INFO -> build\bdist.win-amd64\egg\EGG-INFO
copying UNKNOWN.egg-info\SOURCES.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying UNKNOWN.egg-info\dependency_links.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying UNKNOWN.egg-info\top_level.txt -> build\bdist.win-amd64\egg\EGG-INFO
writing build\bdist.win-amd64\egg\EGG-INFO\native_libs.txt
zip_safe flag not set; analyzing archive contents...
kiwisolver.__pycache__._cext.cpython-311: module references __file__
creating 'dist\UNKNOWN-0.0.0-py3.11-win-amd64.egg' and adding 'build\bdist.win-amd64\egg' to it
removing 'build\bdist.win-amd64\egg' (and everything under it)
Processing UNKNOWN-0.0.0-py3.11-win-amd64.egg
creating d:\workspace\python311\lib\site-packages\UNKNOWN-0.0.0-py3.11-win-amd64.egg
Extracting UNKNOWN-0.0.0-py3.11-win-amd64.egg to d:\workspace\python311\lib\site-packages
Adding UNKNOWN 0.0.0 to easy-install.pth file

Installed d:\workspace\python311\lib\site-packages\unknown-0.0.0-py3.11-win-amd64.egg
Processing dependencies for UNKNOWN==0.0.0
Finished processing dependencies for UNKNOWN==0.0.0

**Comment by MatthieuDartiailh** [comment]
Kiwi uses PEP 517 and requires to be installed using pip as documented. Let me know if you encounter any further issues.

**Comment by tomdog2016** [comment]
It's worked, thank you.
