### ISSUE TITLE
ERROR: Failed building wheel for kiwisolver: C2440: 'static_cast': cannot convert from 'expr_type' to 'type'

### ISSUE THREAD

**Issue by Bluscream** [nucleic/kiwi#151]
https://gist.github.com/Bluscream/49b5721c12327db6a06b84b40217f00d

**Comment by MatthieuDartiailh** [comment]
kiwi requires 3.11.0.b4 at least and now that the rc1 is out I would suggest you update to it. I will try to release wheels ASAP but they will be based on the RC1.

**Comment by MatthieuDartiailh** [comment]
Wheels for RC1 are available on PyPI
