### ISSUE TITLE
Missing type hint for `Constraint.violated()`

### ISSUE THREAD

**Issue by gsingh93** [nucleic/kiwi#165]
`pyright` is telling me that `Constraint` has no member called `violated`. This seems to be missing from `_cext.pyi`. I can add this later but it may be a while, so if anyone else wants to fix this go ahead.

**Comment by Qix-** [comment]
Yeah sorry, I must have missed that in my PR. Original commit here, for anyone wondering: 9c46f893ae3ac6f239d1a7bfccb8bf316ff02293

Just to make things easier, it takes no arguments and returns a `bool`.
