### ISSUE TITLE
Python 3.12 manylinux wheels

### ISSUE THREAD

**Issue by hrnciar** [nucleic/kiwi#167]
Hello.

Could you please release CPython 3.12 manylinux wheels on PyPI?

Python 3.12.0 release candidate 1 was released two weeks ago: https://www.python.org/downloads/release/python-3120rc1/

It should be quite safe to release wheels for a release candidate. ABI for Python 3.12 should be frozen from now on, even for bugfixes. From release notes:

> There will be no ABI changes from this point forward in the 3.12 series, and the goal is that there will be as few code changes as possible.

Thank You.

**Comment by MatthieuDartiailh** [comment]
The wheels have been uploaded

**Comment by hrnciar** [comment]
Thank you!
