### ISSUE TITLE
PyPy support

### ISSUE THREAD

**Issue by jfuruness** [nucleic/kiwi#184]
I'm not sure if you guys support PyPy but this is failing to install on PyPy3.10. I'm using the latest version of kiwisolver on github. See attached error.
[out.txt](https://github.com/user-attachments/files/16714897/out.txt)

**Comment by MatthieuDartiailh** [comment]
This was addressed in #182. I will try to upload the wheels ASAP.

**Comment by jfuruness** [comment]
Thank you!

**Comment by jfuruness** [comment]
PyPy/distutils or whatever it was fixed their backwards compatibility breaking change. As long as everyone updates to the latest PyPy this won't error out anymore. Going to close this issue. https://github.com/pypa/distutils/issues/283
