### ISSUE TITLE
Add dependency on msvc-runtime?

### ISSUE THREAD

**Issue by bdlucas1** [nucleic/kiwi#192]
I encountered the error with missing DLLs while loading kiwisolver (via matplotlib via pyvista). Your documentation suggests to install MSVC build tools. This didn't work for me, and in any case I didn't want to burden the users of my application (diff3d) with that, especially as I wanted to reach less skilled users. 

However I came across another solution: install the msvc-runtime package, which installs those DLLs in a place where Python can find them. I added this as a platform-specific dependency for my app, and now users have only to pip install diff3d. 

Would it make sense for kiwisolver to likewise add msvc-runtime as a platform-specific dependency?

**Comment by MatthieuDartiailh** [comment]
1.4.8 which was just released fixes the issue.
