### ISSUE TITLE
Inconsistent state

### ISSUE THREAD

**Issue by SylvainCorlay** [nucleic/kiwi#20]
On large LPs I have seen the kiwi solver return values that don't satisfy the constraints even though the problem is feasible. We then remain in such an inconsistent state after further changes of the constraints. Reseting the solver seems to solve the issue.

**Comment by sccolbert** [comment]
Can you please provide a reproducible test case. As small as possible preferably :)

Also, Kiwi should never return bad values, if it can't find a solution it should throw an unsatisfiable constraint exception. Are you perhaps eating an exception somewhere?

**Comment by SylvainCorlay** [comment]
Yes, I am trying to get a small example that triggers it. Will get back to you.

**Comment by starwing** [comment]
@sccolbert Hi, I have found a inconsistent test, with the code below:

```cpp
#include "kiwi.h"

#include <stdio.h>

using namespace kiwi;

int main(void)
{
    Variable xl("xl"), xm("xm"), xr("xr");
    Solver solver;

    solver.addConstraint(xm*2 == xl + xr);
    solver.addConstraint(xl + 10 <= xr);
    solver.addConstraint(xr <= 100);
    solver.addConstraint(xl >= 0);

    solver.updateVariables();
    printf("%g, %g, %g\n", xl.value(), xm.value(), xr.value());

    solver.addEditVariable(xm, strength::strong);
    solver.updateVariables();
    printf("%g, %g, %g\n", xl.value(), xm.value(), xr.value());
    
    solver.suggestValue(xm, 70);
    solver.updateVariables();
    printf("%g, %g, %g\n", xl.value(), xm.value(), xr.value());
    
    return 0;
}
```

I have found this [here](https://github.com/Nocte-/rhea/issues/47), this is the examples in the Cassowary algorithm [paper](https://constraints.cs.washington.edu/solvers/uist97.pdf).

could give some help about this? I'm trying implement this algorithm in pure Lua language and meet this issue.

**Comment by sccolbert** [comment]
(40, 70, 100) is a solution to the problem, and so is (65, 70, 75), and so is (30, 50, 70). There may also be many more valid solutions. 

The problem as-written is underconstrained, so kiwi is just going to pick one of the solutions. Which one is picked is more or less random.

If your second constraint was `==` instead of `<=`, or if you added another constraint to pin one of the values, you would get your desired solution.

Kiwi appears to be behaving as designed here.

**Comment by starwing** [comment]
@sccolbert okay, my fault :( I just realize this fact, sorry for noise

**Comment by MatthieuDartiailh** [comment]
Closing as it appears to be normal
