### ISSUE TITLE
I want to add a callback to Variable, so I can update widget's attribute effected.

### ISSUE THREAD

**Issue by yihuang** [nucleic/kiwi#24]
I can hack the source and add a callback function to ``Variable`` easily, but I want to here your opinion on this, is there a more proper way to do this.
I saw a ``Context`` in ``Variable``, but it's not used. I wonder what's the purpose of ``Context``.

**Comment by sccolbert** [comment]
`context` is there for you store anything you want to be associated with a variable. It can be any Python object, so storing a function there would be fine.

**Comment by yihuang** [comment]
What I want is a way to update effected widgets attributes when variable's value changed. I can think of two ways:
1, Associate the widget attribute with variable with ``context`` attribute, and iterate ``solver->m_impl->m_vars`` and apply variable value to widget attribute, after calling ``updateVariables``.
2, Hack ``Variable::setValue`` method to set the value to widget attribute immediately.

Either way, I need to hack kiwi's source code somehow.

**Comment by sccolbert** [comment]
What widgets are you talking about, and what attribute do you want to set? 

If you are using Kiwi directly on your own, you know when you call `updateVariables`, so you can just iterate your variables then. If you are talking about Enaml's widgets, you may be better off hooking into its layout system rather than hacking Kiwi's source.

Basically, I need to know more about what you are trying to do before I can give you better advice.

**Comment by yihuang** [comment]
I'm using kiwi on my own, and I want to only update the attributes that are constrained rather than all the variables defined by widget.
For example, each widget defines ``left, top, width, height``, but for some widgets I only add a constraint for ``width`` and ``height``, and want to set the ``left`` and ``top`` manually.
So I can only iterate the variables in ``solver->m_impl->m_rows`` rather than all the variables defined by the widgets.

**Comment by yihuang** [comment]
PS, I find that there is a problem with ``solver->m_impl->m_vars``, is that it's never get removed except when reset the solver. So If I keep adding and removing constraints, the m_vars keep growing.

**Comment by sccolbert** [comment]
`m_impl` is `private` and not part of the public API.

**Comment by sccolbert** [comment]
If you want to set `left` and `top` of your widgets manually, you are free to do so. I'm not really seeing how this is an issue with Kiwi.

**Comment by yihuang** [comment]
The problem is I have no way to know which variable is constrained and which not (except through private ``m_impl->m_rows`` I guess). 

If I choose the enaml way to do this, then the ``left`` and ``top`` would be reseted to zero every time re-layout:

```
        """ Update the geometry of the underlying toolkit widget.
        This should not be called directly by user code.
        """
        d = self.constrainable()
        x = d.left.value()
        y = d.top.value()
        w = d.width.value()
        h = d.height.value()
        self.set_geometry(x, y, w, h)
```

**Comment by yihuang** [comment]
I've changed ``Variable``'s initial value to ``NAN``, and set the value to ``NAN`` if not found in ``m_rows``, so I can detect the un-constrained variables.
Here's the diff in case you are interested.
```
diff --git a/libs/kiwi/kiwi/solverimpl.h b/libs/kiwi/kiwi/solverimpl.h
index 33b0711..fd517cc 100644
--- a/libs/kiwi/kiwi/solverimpl.h
+++ b/libs/kiwi/kiwi/solverimpl.h
@@ -10,6 +10,7 @@
 #include <limits>
 #include <memory>
 #include <vector>
+#include <cmath>
 #include "constraint.h"
 #include "errors.h"
 #include "expression.h"
@@ -305,7 +306,7 @@ public:
 			Variable& var( const_cast<Variable&>( var_it->first ) );
 			row_iter_t row_it = m_rows.find( var_it->second );
 			if( row_it == row_end )
-				var.setValue( 0.0 );
+				var.setValue( NAN );
 			else
 				var.setValue( row_it->second->constant() );
 		}
diff --git a/libs/kiwi/kiwi/variable.h b/libs/kiwi/kiwi/variable.h
index 525f434..e4de813 100644
--- a/libs/kiwi/kiwi/variable.h
+++ b/libs/kiwi/kiwi/variable.h
@@ -8,6 +8,7 @@
 #pragma once
 #include <memory>
 #include <string>
+#include <cmath>
 #include "shareddata.h"


@@ -91,13 +92,13 @@ private:
 			SharedData(),
 			m_name( name ),
 			m_context( context ),
-			m_value( 0.0 ) {}
+			m_value(NAN) {}

 		VariableData( const char* name, Context* context ) :
 			SharedData(),
 			m_name( name ),
 			m_context( context ),
-			m_value( 0.0 ) {}
+			m_value(NAN) {}

 		~VariableData() {}

```

**Comment by sccolbert** [comment]
You said you are using kiwi on your own. So you should know if the variables are constrained or not because you added them to the solver.

**Comment by sccolbert** [comment]
You can also just added a constraint for the `left` and `top` values to constrain them to what you want e.g.: `left == 42, top == 78`

**Comment by yihuang** [comment]
Updating a constraint is more expensive, since it could be an animation or scrollview updating it every frame.
Traversing the constraint structure to find out what variables it uses is doable i think.

**Comment by sccolbert** [comment]
You can also set an override flag on your widget, and check that before applying the constraint variable values. If the flag is set, ignore the constraint values and use the override values. There's lot's of ways you could solve this without hacking into the kiwi source.

**Comment by yihuang** [comment]
Setting a flag is another useful feature I think, but I still think checking the NAN is a good default behaviour, thanks for your suggestions ;D

**Comment by hfossli** [comment]
Checking for NAN values doesn't cover a situation where constraints have been added and then removed later. The variables may still be underconstrained..
