### ISSUE TITLE
No way to weight constraints of equal strength

### ISSUE THREAD

**Issue by helmesjo** [nucleic/kiwi#25]
As far as I know, the default implementation of Cassowary allows for "weighting" constraints of equal strength. 
In short: If two constraints of equal strength existed and both can't be satisfied at once, the one with greater weight would be prioritized. 

Why has this been opted out?

**Comment by sccolbert** [comment]
In the original implantation, the strength is just multiplied by the weight to produce a final strength for the constraint when adding it to the solver. I just omittted that and consider the strength to be pre-multipled

**Comment by sccolbert** [comment]
In particular, notice the optional 4th arg weight arg to `create_strength`, which defaults to `1.0`:

C++:
https://github.com/nucleic/kiwi/blob/master/kiwi/strength.h#L18

Python:
https://github.com/nucleic/kiwi/blob/master/py/strength.cpp#L77

**Comment by helmesjo** [comment]
Alright thanks, I'll have a look at it!
