### ISSUE TITLE
License

### ISSUE THREAD

**Issue by hfossli** [nucleic/kiwi#27]
Would you consider switching to MIT license? I love MIT for its simplicity.

**Comment by sccolbert** [comment]
What would be the benefit of this? The BSD license is simple as well.

**Comment by hfossli** [comment]
Yes, it is simple as well. I generally prefer the MIT license because it does not require attributions in binary fo

**Comment by hfossli** [comment]
MIT is familiar to many people as it is used on [44% (!) of all projects on github](https://github.com/blog/1964-open-source-license-usage-on-github-com).

I think [this stackoverflow](http://programmers.stackexchange.com/questions/82321/why-do-people-pick-the-mit-license-over-bsd-if-bsds-non-endorsement-clause-i) post sums it up quite nicely as well 

> The MIT license is widely understood to mean "you can do whatever you wish with this code". 

> If you're scared of having your name dragged through the mud, then the BSD license will seem better. If you're scared of having your software put into a proprietary piece of software, then the GPL will seem better. Whatever the license, the author chooses it because it protects them against what they are afraid of.

> Different people have different concerns and so use different licenses.

**Comment by MatthieuDartiailh** [comment]
As all project under nucleic uses BSD I do not see a strong incentive to switch.
