### ISSUE TITLE
unknown vars count

### ISSUE THREAD

**Issue by quaikohc** [nucleic/kiwi#31]
hi,
thanks for great library, I am trying to use it for my gui layout and I'm stuck with simple problem: the position and size of my widgets are kiwi Variables, i don't know how many of them (widgets) there will be, but to calculate the proper layout  i need a constraint that deals with them all, for example i want to say that the sum of the widths of all widgets should be equal to the size of the parent widget, how can i do that?

i want' to write sth like that
solver.addConstraint( width0 + width1 + width2 + (...) == parentWidth);

cheers

**Comment by sccolbert** [comment]
It can get fairly complex depending on how much of a "layout system" you want to build.

Here are the gritty details for how we generate constraints in Enaml:
https://github.com/nucleic/enaml/tree/master/enaml/layout

Those helpers are the "engine" which allow us to have things like `vbox(*widgets)`:
https://github.com/nucleic/enaml/blob/master/enaml/widgets/v_group.py#L60-L61
https://github.com/nucleic/enaml/blob/master/enaml/layout/layout_helpers.py#L64
https://github.com/nucleic/enaml/blob/master/enaml/layout/linear_box_helper.py#L31

For your simple case exactly, you can use a simple sum:
`solver.addConstraint(sum([item.width for item in items]) == parentWidget)`

**Comment by quaikohc** [comment]
Thanks. Sorry but can you explain how can i do this in c++?

**Comment by hfossli** [comment]
You could build an `Expression` of `Term`s and create a constraint where that expression is set to equal `parentWidth`.

In swift I would (pseudo)
```swift
let width0 = Variable()
let width1 = Variable()
let width2 = Variable()
let allWidths = Expression([Term(width0), Term(width1), Term(width2)])
let constraint = allWidths == parentWidth
solver.addConstraint(constraint)
```

**Comment by sccolbert** [comment]
You can do like @hfossli said, using an `std::vector` of `Term` objects:
https://github.com/nucleic/kiwi/blob/master/kiwi/expression.h#L26

Or use a simple loop to accumulate the expression (but that will be more expensive).
