### ISSUE TITLE
Can cassowary solve for modulo and modulus?

### ISSUE THREAD

**Issue by Qix-** [nucleic/kiwi#35]
So the two operations that would make a lot of constraints easier to model (some of which are impossible without) are modulo (`a % b`) and modulus (absolute value, or `|a|`). I know the absolute value one might be tricky API-wise since there's no operator for it, though `a == b.abs()` would be acceptable I would think.

Is this something the solver could actually solve? The operations are a bit much for me to comprehend without understanding cassowary at its core I feel like, or else I'd either 1) know the answer, or 2) submit a PR.

**Comment by hfossli** [comment]
What's the use case?

**Comment by Qix-** [comment]
@hfossli We're (ab)using cassowary for something other than UIs and need to fit something to a very specific integer value. AFAICT everything is double-oriented, so doing something like `id == abs(calculated_value)` is tricky.

**Comment by Qix-** [comment]
And to be honest, exponents would be pretty useful too.

**Comment by sccolbert** [comment]
The Cassowary algorithm is a linear constraint solver:
https://en.wikipedia.org/wiki/Linear_programming

The modulus operator and `abs` are both non-linear operations, which cannot be handled by the solver.
