### ISSUE TITLE
STL containers are too slow in debug

### ISSUE THREAD

**Issue by jimon** [nucleic/kiwi#38]
I have around 200 variables and 2000 constraints, this works ok in release (takes around 0.2s to add everything), but times in debug are ridiculous: around 7s. After profiling a bit, it looks like all the time is taken in STL/Loki stuff:

![image](https://user-images.githubusercontent.com/1333661/29709483-c7931748-898c-11e7-8d18-b1ef2fdb32de.png)

Would be nice to workaround it somehow, maybe using custom memory efficient containers? Or maybe add ability to prepare solver state in offline and just load it as-is in online without doing much work.

**Comment by sccolbert** [comment]
I'm really not sure why this is a problem. Debug builds shouldn't be used in production. They are for debugging so will always be much slower than release builds.
