### ISSUE TITLE
py27+kiwi doesn't like `from __future__ import unicode_literals`

### ISSUE THREAD

**Issue by jklymak** [nucleic/kiwi#39]
The following fails when using python 2.7 (works fine w/ python 3.6).

```python
from __future__ import unicode_literals

import kiwisolver as kiwi

Variable = kiwi.Variable
solver = kiwi.Solver()
top = Variable('boo')
```
with:

```
python testkiwi27.py
Traceback (most recent call last):
  File "testkiwi27.py", line 7, in <module>
    top = Variable('boo')
TypeError: __new__() argument 1 must be string, not unicode
```

If I remove the `__future__` it works fine, but the project I'm working with uses the future, so I can't really remove it (matplotlib).  

I can cast all kiwi string arbuments to `String`,  but maybe its a better solution for kiwi to recognize Unicode or do the cast itself?

Other string arguments fail as well (i.e. the strength arguments).

Thanks!

**Comment by MatthieuDartiailh** [comment]
Yes kiwi wants bytestring under Python 2. I did not change this behavior when porting to Python 3. @sccolbert what do you think ? Should we support unicode ?

**Comment by sccolbert** [comment]
I think this can be fixed by just removing the Python 2 block from this `if` clause, and use the Python 3 logic for everything (since it's Py2 compatible):
https://github.com/nucleic/kiwi/blob/master/py/variable.cpp#L25-L37

**Comment by jklymak** [comment]
Thanks a lot to both @sccolbert and @MatthieuDartiailh  for all your work on this.  I feel a little bemused to have my name attached to it, as it quickly got out of my depth!
