### ISSUE TITLE
Changing expression constant

### ISSUE THREAD

**Issue by yglukhov** [nucleic/kiwi#41]
Hello, what is the proper way to animate the constraint? With iOS/MacOS auto layout you would normally animate the constant of an already added constraint, but I can't see a proper way to do it with kiwi.

**Comment by yglukhov** [comment]
Another option would be to allow some kind of variables which can be changed from outside, but not from the solver, but I can't see those in Kiwi as well (

**Comment by MatthieuDartiailh** [comment]
I believe what you are looking for are EditVariables. You can look at cassowary examples as kiwi implement the same solver. This example in particular seems to describe your use case: http://cassowary.readthedocs.io/en/latest/topics/examples.html

**Comment by yglukhov** [comment]
@MatthieuDartiailh, I doubt it. The example you're providing is using stay constraints (grep for add_stay), which is missing in kiwi.

To somehow rephrase my question I can provide a use case which I want to implement. Let's say there's a UI system, with view hierarchies, where every view has x, y, width and height variables. All the variables are tied with constraints. Then there's the window with its width and height variables. The user may resize it, so I "edit" the width and height of the window and it works for the first relayout, but subsequent calls to `solver.solve` may randomly change these variables again. So I want those variables to *stay* and be changed when its otherwise impossible to solve the constraints.

**Comment by MatthieuDartiailh** [comment]
I believe you can still achieve your goal without stay constraints, as it is done in enaml (https://github.com/nucleic/enaml/blob/master/enaml/layout/layout_manager.py#L244). You can look at how the constraints are defined and how resize is done.
I must say I am not an expert here, @sccolbert would be more qualified to answer you.

**Comment by MatthieuDartiailh** [comment]
See also this discussion https://github.com/nucleic/kiwi/issues/9

**Comment by yglukhov** [comment]
Thanks, #9 explains a lot. Maybe this info should be mentioned on the front page, that stay constraints can be "simulated" by adding/removing external EQ constraints.

**Comment by sccolbert** [comment]
@yglukhov The right way to do what you want is with edit variables. In Enaml, each widget has a variable for `left`, `right`, `width`, and `height`. Child widgets are ultimately constrained based on their parent's `width` and `height` variables. Those variables are added to the solver via `solver.addEditVariable`. When solving for the layout of the children, the current size of the parent is used to suggest values for the `width` and `height` variables via `solver.suggestValue`. The system is then solved via `solver.updateVariables`.

https://github.com/nucleic/enaml/blob/master/enaml/layout/layout_manager.py#L358-L360

**Comment by yglukhov** [comment]
@sccolbert, ah that makes even more sense. Thank you. Still worth mentioning in the docs I think.
