### ISSUE TITLE
Testing an installed kiwisolver

### ISSUE THREAD

**Issue by matthew-brett** [nucleic/kiwi#44]
Thanks for the package.

@tacaswell pointed me here, to ask if I could help with building wheels, so we can use kiwi for Matplotlib.

I had a quick shot, but there is a problem I would like to ask your advice on:

I don't think it's possible to test an installed `kiwisolver`.  At least, when I try:

```
pip install .
mkdir tmp
cd tmp
py.test --pyargs kiwisolver
```

I get:

```
=============================================================== test session starts ===============================================================
platform darwin -- Python 3.5.1, pytest-3.4.0, py-1.5.2, pluggy-0.6.0
rootdir: /Users/mb312/dev_trees/kiwisolver-wheels/kiwi, inifile:
collecting 0 items                                                                                                                                
========================================================== no tests ran in 0.00 seconds ===========================================================
ERROR: not found: /Users/mb312/.virtualenvs/test3/lib/python3.5/site-packages/kiwisolver.cpython-35m-darwin.so
(no name '/Users/mb312/.virtualenvs/test3/lib/python3.5/site-packages/kiwisolver.cpython-35m-darwin.so' in any of [])
```

This is a killer for wheels, because we obviously want to make sure that the installed wheel is functioning correctly, before shipping.  Do you have any suggestions?

**Comment by matthew-brett** [comment]
Here's the same thing happening in the wheel-building repo: https://travis-ci.org/MacPython/kiwisolver-wheels/jobs/338136621#L616

**Comment by MatthieuDartiailh** [comment]
Looks like you solved it in the matplotlib thread. kiwisolver does not package the tests with the library so you need to run them from the sources.

**Comment by matthew-brett** [comment]
I would say we worked around the problem, rather than solving it.  I was just flagging it here because, for my own projects, I like to make it possible to run the tests on the installed package, for debugging and to reassure the user.

**Comment by MatthieuDartiailh** [comment]
For projects with multiple components and backends like matplotlib or numpy I agree that verifying that all parts work well together make sense, but for smaller projects I find that including the tests is not really necessary. If this is something you really need I can consider adding them to the release, but I am not convinced it is needed.

**Comment by matthew-brett** [comment]
I tend to ship them, because when a user says "it's not working" I can say "what do you get from a test run?".   But if you don't think that's important, that's fine, the workaround is fine for the wheel building.
