### ISSUE TITLE
Provide wheel for linux_armv7l

### ISSUE THREAD

**Issue by seanpianka** [nucleic/kiwi#49]
Hi Nucleic Team!

I'm building a system for an embedded `linux_armv7l` platform. It makes use of scikit-image, which has kiwi as a dependency.

Is there anyway you could find it in your heart to build a wheel for this platform/architecture? I'm struggling greatly to manually build a wheel as the platform does not come equipped with a toolchain (and installing one is off the table).

Thanks for reading, and I hope to hear from someone soon! :smile:

**Comment by MatthieuDartiailh** [comment]
Sorry for taking this long to answer.
Honestly I can make no promise, but I will try to look into it. From some reading using a Docker image properly configured may be the easiest solution (using CircleCI for example). It might be possible for you to build the wheel yourself and use a private wheelhouse.

**Comment by kevinastone** [comment]
There's a wheel built by piwheels:

https://www.piwheels.org/project/kiwisolver/

**Comment by MatthieuDartiailh** [comment]
Good to know !

**Comment by MatthieuDartiailh** [comment]
We know have wheel for aarch64 too on PyPI.
