### ISSUE TITLE
Add "Programming Language :: Python :: 3" to PyPI metadata

### ISSUE THREAD

**Issue by slel** [nucleic/kiwi#63]
Add "Programming Language :: Python :: 3" to PyPI metadata...
... and get a green badge on the [Python3 wall of superpowers](https://python3wos.appspot.com/)

**Comment by MatthieuDartiailh** [comment]
Those are now present but have never been included in a release hence pypi confusion.

**Comment by slel** [comment]
The "Python 3 wall of superpowers" no longer gets updated anyway.
A release with the "Python :: 3" tag on PyPI should however help make
["Can I use Python3"](https://caniusepython3.com/project/kiwisolver) happy.

**Comment by cclauss** [comment]
A new release would be a good idea.

**Comment by MatthieuDartiailh** [comment]
I am planning one, in the next month or so. I will keep you posted. Thanks for your interest.

**Comment by MatthieuDartiailh** [comment]
Closed by 1.1.0 release.
