### ISSUE TITLE
New release could use wheels for pypi...

### ISSUE THREAD

**Issue by jklymak** [nucleic/kiwi#65]
Previous wheels were discussed #48, but not sure if the process was automated?  I'd help, but it looks like @matthew-brett has it set up and I've not made wheels before...

This break pip installs for mac folks trying to use matplotlib: https://github.com/matplotlib/matplotlib/issues/14031

**Comment by jklymak** [comment]
PS Thanks a lot for the new release!

**Comment by MatthieuDartiailh** [comment]
The wheels have been uploaded (the gap between the source release and the wheels was only a couple of hours).

**Comment by jklymak** [comment]
Thanks my apologies I should have actually checked if they were there before opening a ticket.

**Comment by matthew-brett** [comment]
Thanks much for uploading the wheels.

Could we humbly ask if you'd consider a policy of uploading the wheels first?  I'm very happy to help with any tooling.

**Comment by MatthieuDartiailh** [comment]
Sounds reasonable @matthew-brett I will try to remember that for future releases.

**Comment by matthew-brett** [comment]
Thanks - that would be very helpful - and sorry for the extra burden.
