### ISSUE TITLE
"ImportError: DLL load failed" on fresh Windows 10 installation

### ISSUE THREAD

**Issue by jonascj** [nucleic/kiwi#69]
I was trying to import matplotlib (which uses kiwisolver) and it failed with `ImportError: DLL load failed` and it turned out it was kiwisolver which actually failed to import.

The problem was solved by installing Microsoft Visual C++ redistributable 2015. Some dependencies (maybe fore precompiled binaries) must have been missing on the fresh/clean install of Windows 10.

See also: 
https://stackoverflow.com/a/38350913/4993453
https://github.com/matplotlib/matplotlib/issues/14303

**Comment by MatthieuDartiailh** [comment]
Sadly I cannot embed Microsoft Visual C++ redistributable 2015 (or 2017 which is binary compatible) in the wheels. The best I can do is add a detailed explanation of the issue and of how to fix it in the documentation.

**Comment by MatthieuDartiailh** [comment]
I will close when the documentation will have been updated.

**Comment by jonascj** [comment]
I'm not a regular Windows user, still now I feel dumb for not looking for a Windows library dependency analyzer, that would have saved me a ton of trying and searching:  http://www.dependencywalker.com/

Updating the documentation is as good as it gets I think. Nothing can be done to show "you are likely missing Microsoft Visual C++ redistributable 2015/2017" on import errors, right? Apart from maybe making a wrapper module which imports the real deal and throws that message ...

**Comment by MatthieuDartiailh** [comment]
I don't fancy adding a Python module to handle that kind of error report. However matplotlib could add such a safety around the import of kiwisolver. Something along the following lines:
```python
try:
    import kiwisolver as kiwi
except ImportError as ex:
    if sys.platform == 'win32' and 'DLL' in ex.msg:
        msg = ('You may be missing Microsoft Visual C++ redistributable '
               'matching your Python version. Consult Kiwisolver '
               'documentation for more details.'
        raise ImportError(msg) from ex
    else:
        raise
```

I do not have access to a windows machine on which to test anytime soon @jonascj . Could you test and open a PR against matplotlib ?

**Comment by jonascj** [comment]
Sure could, I actually just suggested something similar here: 

https://github.com/matplotlib/matplotlib/issues/14315

And that should be added the first place kiwisolver is imported, I think that is in `_check_versions()` in `lib/matplotlib/__init__.py`, at least that is what throws the error.

**Comment by jonascj** [comment]
Your suggested code works, thanks. I submitted a PR containing it: https://github.com/matplotlib/matplotlib/pull/14316
