### ISSUE TITLE
Many-constraints issue

### ISSUE THREAD

**Issue by jklymak** [nucleic/kiwi#71]
OK, more a question than an issue...  I don't think anything is buggy per-se, but would appreciate some advice.

In matplotlib we do the layout using kiwi, and it works quite well.  

However, I am trying to add a constraint to set the aspect-ratio of an axes: (i.e. `c  = axlb.width == aspect * axlb.height | strength`), and suddenly the solver cannot handle this for many axes.  For example 10x10 works fine w/o this extra constraint; but 5x5 won't converge with this constraint; 4x4 does converge, and the constraints work as expected, so I think I did them properly.  By "won't converge" I mean it either just sits and spins until I kill the process, or it returns with and "unbounded" solution error.  

I *think* what is happening is that the problem was independent in x and y before.  i.e. the width calculations never needed to know about the height calculations, though I never consciously separated them.  So I think the solver is solving something like 2*N problem.  

However, when I introduce the constraint above, suddenly the widths and heights depend on each other, and I think the problem effectively blossoms to an N-squared problem.  

The fact of the matter is that the overall layout doesn't particularly care about this new constraint - its an inner "box" that has one of its two dimensions constrained by the parent box size, and the other one by the aspect ratio.  The parent box size doesn't change due to this inner box - the only reason I need the inner box is to line up the top of a colorbar with it.

So, have I just run up against a limitation of kiwi? Or is there something I should be doing to make this more robust? We could just say "you can't do that w/ a 5x5 array of axes" but that is hard to enforce.

**Comment by MatthieuDartiailh** [comment]
As usual it would be best to have @sccolbert opinion on this but I believe that you should try to avoid building over-large systems. Typically enaml use one solver per container to keep the system size reasonable. In your case it sounds like you could break the problem in multiple pieces which is likely to give better results. 

I never had time to look at your implementation but I still hope to do so at one point now that I spent sometime in enaml codebase to write the documentation.

**Comment by jklymak** [comment]
@MatthieuDartiailh Thanks!  My implementation probably needs another set of eyes.  Its seems pretty robust for most conditions, but maybe there are serious design flaws...  I've not used a constraints system before, so probably made a bunch of mistakes.

In this case, I understand what you are suggesting about nesting the solvers, but I'm not sure that's practical.  Basically, in the horizontal, everything I'm specifying needs to be part of the constraints.  A good number of constraints are *redundant* given the grid layout (i.e. the left edge of each axes in a column is the same, and if the axes span the same number of columns, their widths are the same)  so perhaps there is room for optimization there.  But that would make the code a lot more complicated.

**Comment by MatthieuDartiailh** [comment]
It is by no means perfect but you can have a look at my description pf enaml system in kiwi docs. I agree the code may end up beong more convoluted (enaml is), but it may be the price. My plate is quite full at the moment but I will try to have a look next week or the week after. Don't hesitate to ping me if you do not hear from me.

**Comment by sccolbert** [comment]
Rather than have constraints for each item in the grid, you can create
virtual row and column objects and set constraints on those. This shrinks
the N^2 problem to 2*N. Once you solve the system, it's just a matter of
making a double for-loop over the rows and columns, and assigning the
geometry to the correct cell item.

**Comment by sccolbert** [comment]
you might take inspiration from here:
https://github.com/nucleic/enaml/blob/master/enaml/layout/grid_helper.py

**Comment by jklymak** [comment]
Thanks @sccolbert  Not sure I can really do that since in this iteration the width of some objects depends on the height, and neither are known.  

A related question:  I have a few "helper" Variables with constraints like `axlb.width == axlb.right - axlb.left | 'required'`.  These could all be removed, but would that help the solution be more manageable?

**Comment by sccolbert** [comment]
You should still be able to do it how I suggest, given that each cell in a
row will be the same height and each cell in a column the same width. What
you do within that allocated cell space can be handled on a per-cell basis.

**Comment by sccolbert** [comment]
You may need to do a two pass layout, one system to solve for the heights,
and another to solve for the widths using the computed heights as input.

**Comment by MatthieuDartiailh** [comment]
@jklymak I belive you fixed your issue now in matplotlib correct ? Would you mind providing a quick conclusion to this issue ?

**Comment by jklymak** [comment]
Not directly - I did a rewrite that had far fewer constraints.  Always goes better the second time around ;-).  OTOH I don't think the new system will take into account ratios, so this can certainly be closed.
