### ISSUE TITLE
package requirements: setuptools

### ISSUE THREAD

**Issue by Blizarre** [nucleic/kiwi#72]
Hi,

when we packaged kiwisolver with conda we discovered that the package has a dependency to `setuptools`.

Is this dependency really required for kiwisolver to run? I cannot see any use of the package anywhere in the source code.

**Comment by Qix-** [comment]
https://github.com/nucleic/kiwi/blob/master/setup.py

**Comment by Blizarre** [comment]
I know that it is described in `setup.py`, but my question is "is it really needed for anything in kiwi?"

It is described in the `install_requires`:
```install_requires is a setuptools setup.py keyword that should be used to specify what a project minimally needs to run correctly```
https://packaging.python.org/discussions/install-requires-vs-requirements/

**Comment by Qix-** [comment]
Oh I see, yeah it should be removed IMO. I don't see why it'd be required.

**Comment by MatthieuDartiailh** [comment]
It is an artifact of a time when the distutils/setuptools situation was less clear. I will fix it for the next release.

Regarding vonda kiwisolver is already packaged and available on the default and conda-forge channels.
