### ISSUE TITLE
Python 3.8 (pip) - no pre-built wheel package

### ISSUE THREAD

**Issue by jite** [nucleic/kiwi#75]
I don't know if this is the proper place for this issue, however when trying to do a
`pip install kiwisolver` using Python 3.8 there's no pre-built wheel package available, thus forcing pip to download the .tar.gz src code and trying to build it.

**Comment by MatthieuDartiailh** [comment]
I had no time to test kiwi on 3.8 yet. If it turns out that the current release supports it, I will upload the relevant wheels. Please note it may take me a couple of weeks.

**Comment by MatthieuDartiailh** [comment]
The missing wheels are now online for 1.1.0

**Comment by jite** [comment]
Thanks, and thanks for the quick response.
