### ISSUE TITLE
looking for a way to build a constraint from an arbitrary number of variables

### ISSUE THREAD

**Issue by pauldavisthefirst** [nucleic/kiwi#85]
struct  Foo { Foo() {} kiwi::Variable var; }
std::vector&lt;Foo&gt; foos;
for (int n = 0; n < 10; ++n) { foos.push_back (Foo()); }

/* simple case */

Constraint c1 (foos.front().var == 10);

/* complex case */

 ..... want to iterate over everything in foos and build a constraint using the var from each of them ...

/// END

I can't see anyway to do this right now. Am I wrong?

**Comment by Qix-** [comment]
> want to iterate over everything in foos and build a constraint using the var from each of them

Can you give an example of what you mean? You can use `auto` here if you're unsure about Kiwi's `Term`, `Expression` and `Constraint` types.

**Comment by MatthieuDartiailh** [comment]
The recently added c++ benchmarks provide detailed example of how to perform this task. Closing given the lack of activity.
