### ISSUE TITLE
Deprecation warning due to invalid escape sequences

### ISSUE THREAD

**Issue by tirkarthi** [nucleic/kiwi#86]
Deprecation warnings are raised due to invalid escape sequences. This can be fixed by using raw strings or escaping the literals. pyupgrade also helps in automatic conversion : https://github.com/asottile/pyupgrade/

```
py/tests/test_constraint.py:31
  /root/checked_repos/kiwi/py/tests/test_constraint.py:31: DeprecationWarning: invalid escape sequence \*
    constraint_format = '1 \* foo \+ 1 %s 0 | strength = 1.001e\+[0]+9' % op
```

**Comment by MatthieuDartiailh** [comment]
Thanks, I did not notice that. #87 takes care of the issue.
