### ISSUE TITLE
Stay constraints

### ISSUE THREAD

**Issue by Nocte-** [nucleic/kiwi#9]
I came across this library yesterday, and I'm very impressed how much smaller and faster it is compared to the original implementation! One of the things I noticed is that there are no stay constraints. I always found them a bit of a nuisance, and if it is possible to remove them I'd like to do this as well for my own C++ Cassowary lib, [Rhea](https://github.com/Nocte-/rhea).

How did you redesign stay constraints? Are they implicit for all variables now?

**Comment by helmesjo** [comment]
Is there any way to work around this (read hack), or extend current code base? I'm not very (read barely) familiar with the implementation-details of cassowary & stays, but they are vital in my case since I use the solver in a "drag-n-drop" editor which is at most times under-constrained...

Is it possible without too much trouble?

**Comment by sccolbert** [comment]
You can probably work-around it by adding non-required `==` constraints for the variables which should remain in their current location. When editing parameters, remove the the `==` constraints and use `suggestValue` for the variables which should be edited.

**Comment by helmesjo** [comment]
Yeah thought about that, but I want to avoid this since then I have to keep adding/removing constraints when vars things around which might cause performance issues...

**Comment by hfossli** [comment]
In my experience cassowary is solving things very quickly. I wouldn't worry about performance issues.

**Comment by helmesjo** [comment]
Been having some issues with older implementations which is why I set my hopes for this one, but then again I'm running on mobile devices so every inch counts! 

But yeah I might be able to mimic it with equal-constraints without to much effort... :)

**Comment by hfossli** [comment]
I'm also on mobile c++ (ios). The java implementation seems slower.
