### ISSUE TITLE
Unable to achieve equal distribution

### ISSUE THREAD

**Issue by Folling** [nucleic/kiwi#99]
I would like to use kiwi in a GUI toolkit I'm writing for the layouting concerns.
Testing out with I wanted to solve a rather simple situation:
Two widgets are side-by-side. The total available width is 500px, each widget has a minimum width of 200, a maximum width of 400, and a pref-width of 300.
I tried solving this with the following code:
```cpp
kiwi::Solver solver;
kiwi::Variable width0;
kiwi::Variable width1;
solver.addConstraint(kiwi::Constraint{(width0 + width1) <= 500.0f});
solver.addConstraint(kiwi::Constraint{width0 >= 200.0f | kiwi::strength::required});
solver.addConstraint(kiwi::Constraint{width1 >= 200.0f | kiwi::strength::required});
solver.addConstraint(kiwi::Constraint{width0 <= 400.0f | kiwi::strength::required});
solver.addConstraint(kiwi::Constraint{width1 <= 400.0f | kiwi::strength::required});
solver.addConstraint(kiwi::Constraint{width0 == 300.0f | kiwi::strength::strong});
solver.addConstraint(kiwi::Constraint{width1 == 300.0f | kiwi::strength::strong});
solver.updateVariables();
    
std::cerr << width0.value() << " | " << width1.value() << std::endl;
```
It would feel most natural to me if the final result were `250 | 250`, given that both widgets have an equal poll on the remainder of the size (the strength is equal) that is left-over after the minimum sizes. However this yields `300 | 200`, which is of course a valid solution, just not one I wanted or expected.

Is there a way to tell the solver to respect both constraints equally instead of preferring one over the other?
I attempted using editVariables and suggest 300 for both of them, instead of using `==` constraints. Though that case the result was simply flipped: `200 | 300`.

Reading through some other issues my understanding is that this system is underconstrained. I am however unable to figure out how to constraint it properly. My initial idea was to simply specify that the ratio of `width0` to `width1` need be identical to the ratio of the two preferred sizes, but variables don't have an overload for multiplication/division, so that won't work.
For this specific case of course I could simply require `width0` to be equal to `width1`, but that wouldn't work if the preferred sizes aren't equal - which, in practice, is not going to be the case all that often.

Thanks for your help and time in advance,
Folling

**Comment by Qix-** [comment]
Just a shot in the dark, but have you tried using an `==` constraint with a very weak strength?

**Comment by Folling** [comment]
Yes I have!
I used both `kiwi::strength::weak` and plainly `0.01`.
The results stay the same, though at times they flip from `200 | 300` to `300 | 200`.

**Comment by Folling** [comment]
While we're at it -- I've read in <https://github.com/nucleic/kiwi/issues/35> that the modulo operator cannot be featured since modulo wouldn't constitute a linear operation which doesn't work since Cassowary is strictly a **linear** constraint solving algorithm. Is the same true for multiplication and division? I would have figured those are linear but perhaps I am misunderstanding the term.

**Comment by Qix-** [comment]
No there are definitely operators for that.

https://github.com/nucleic/kiwi/blob/master/kiwi/symbolics.h#L22-L32

Not every combination of term/variable/expression are supported however.

**Comment by Folling** [comment]
Variable/Variable wasn't supported, which was the main thing I needed

**Comment by MatthieuDartiailh** [comment]
@Folling I tried your example and added a weak constraint that should break the tie as was suggested earlier. And contrary to what you report I do observe the expected behavior. Being more of a Python person I attach a Python script demonstrating the working condition.

Regarding multiplication and division between variable, that would indeed introduce non-linearity in the solver (imagine the case x == y and x*y == 2). However `width0 / width0_pref_width == width1 / width_1_pref_width` should work and yield teh result you expect.

As a side node you can have a look at https://github.com/nucleic/enaml for use of kiwi in the context of building a UI. The kiwi documentation provides a quick discussion of this use case also.

Python code:
```python
from kiwisolver import Solver, Variable, strength

solver = Solver()
width0 = Variable("w1")
width1 = Variable("w2")
solver.addConstraint(width0 + width1 <= 500.0)
solver.addConstraint((width0 >= 200.0) | strength.required)
solver.addConstraint((width1 >= 200.0) | strength.required)
solver.addConstraint((width0 <= 400.0) | strength.required)
solver.addConstraint((width1 <= 400.0) | strength.required)
solver.addConstraint((width0 == 300.0) | strength.strong)
solver.addConstraint((width1 == 300.0) | strength.strong)
solver.addConstraint((width0 == width1) | strength.weak)
solver.updateVariables()

print(width0.value(), width1.value())
```

**Comment by Folling** [comment]
Your example works because of
`solver.addConstraint((width0 == width1) | strength.weak)`
Which I addressed in the original post as follows:

> For this specific case of course I could simply require `width0` to be equal to `width1`, but that wouldn't work if the preferred sizes aren't equal - which, in practice, is going not going to be the case all that often.

It does work in this specific scenario, but it wouldn't if the prefered width for the first widget was, say 350, and the one for the second 250.
I expected the remaining "space" so to speak, to be distributed proportionally to the preferred settings specified by the `==` constraint (or the suggested values, it seems to make little difference).

**Comment by MatthieuDartiailh** [comment]
You need to provide a tie breaker since the solver has no notion of preferred size, all constraints are seen as equivalent. The solution you proposed will work as illustrated below:

```python
from kiwisolver import Solver, Variable, strength

solver = Solver()
width0 = Variable("w1")
width1 = Variable("w2")
pw0 = 300
pw1 = 500
solver.addConstraint(width0 + width1 <= 500.0)
solver.addConstraint((width0 >= 200.0) | strength.required)
solver.addConstraint((width1 >= 200.0) | strength.required)
solver.addConstraint((width0 <= 400.0) | strength.required)
solver.addConstraint((width1 <= 400.0) | strength.required)
solver.addConstraint((width0 == pw0) | strength.strong)
solver.addConstraint((width1 == pw1) | strength.strong)
solver.addConstraint((width0 / pw0 == width1 / pw1) | strength.weak)
solver.updateVariables()

print(width0.value(), width1.value())
```

**Comment by MatthieuDartiailh** [comment]
If you think this would be worth a mention in the documentation please feel free to submit a PR.
